### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by rarean** [story-doc/js#1]
What dot program is is this looking for?
```
java.io.IOException: Cannot run program "/opt/local/bin/dot": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123)
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
```

**Comment by rarean** [comment]
Based on this info from GraphViz plantuml is looking this executable
```
java -jar plantuml.jar -testdot
The environment variable GRAPHVIZ_DOT has not been set
Dot executable is /opt/local/bin/dot
Error: File does not exist
Error: only sequence diagrams will be generated
```
So the dependency is GraphViz, which can be installed with
```
brew install libtool
brew link libtool
brew install graphviz
brew link --overwrite graphviz
```

**Comment by story-doc** [comment]
Thank you for the information. I've updated documents.
The Graphviz was not required on my environment, so I did not realize it.
